In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame([[1,2], [3,4], [5,6]], columns=['a', 'b'])

In [4]:
df

   a  b
0  1  2
1  3  4
2  5  6

dictionary

In [6]:
laptop = {
    'Merek'      : ['Lenovo', 'HP', 'Acer', 'Asus'],
    'Kelebihan'  : ['Part Bagus', 'Murah', 'Pilihan Banyak', 'Ergonomis'],
    'Kekurangan' : ['Mahal', 'Plastik Laptop gampang patah', 'Keyboar suka rusak', 'Mesin gampang panas']
}

laptop = pd.DataFrame(laptop)
laptop

    Merek       Kelebihan                    Kekurangan
0  Lenovo      Part Bagus                         Mahal
1      HP           Murah  Plastik Laptop gampang patah
2    Acer  Pilihan Banyak            Keyboar suka rusak
3    Asus       Ergonomis           Mesin gampang panas

List of list

In [7]:
laptop = [
    ['Lenovo', 'Part Bagus', 'Mahal'],
    ['HP', 'Murah', 'Plastik gampang patah'],
    ['Acer', 'Pilihan Banyak', 'Keyboard suka rusak'],
    ['Asus', 'Ergonomis bentuknya', 'Gampang Overheat']
]

laptop = pd.DataFrame(laptop, columns=['Merek', 'Kelebihan', 'Kekurangan'])
laptop

    Merek            Kelebihan             Kekurangan
0  Lenovo           Part Bagus                  Mahal
1      HP                Murah  Plastik gampang patah
2    Acer       Pilihan Banyak    Keyboard suka rusak
3    Asus  Ergonomis bentuknya       Gampang Overheat

List of Dictionary

In [8]:
laptop = [
    {'Merk' : 'Lenovo', 'Kelebihan' : 'Part Laptop Bagus', 'Kekurangan' : 'Mahal'},
    {'Merk' : 'HP', 'Kekurangan' : 'Plastik gampang patah'},
    {'Merek' : 'Acer', 'Kelebihan' : 'Murah'},
    {'Merek' : 'Asus', 'Kekurangan' : 'Gampang panas'}
]

laptop = pd.DataFrame(laptop)
laptop

     Merk          Kelebihan             Kekurangan Merek
0  Lenovo  Part Laptop Bagus                  Mahal   NaN
1      HP                NaN  Plastik gampang patah   NaN
2     NaN              Murah                    NaN  Acer
3     NaN                NaN          Gampang panas  Asus