In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([[1,2], [3,4], [5,6]], columns=['a', 'b'])

In [7]:
df = pd.DataFrame([[1,2], [3,4]], columns=['c', 'x'])

In [8]:
df

   c  x
0  1  2
1  3  4

dictionary

In [13]:
mobil = {
    'Produk' : ['Toyota', 'Mazda', 'Cherry', 'BMW'],
    'Kelebihan' : ['Service Mudah', 'Fun to Drive', 'Murah tapi ga murahan', 'Mewah'],
    'Kekurangan' : ['Pelit Fitur', 'CBU harga mahal', 'Service Bad', 'Service Mahal']
}

mobil = pd.DataFrame(mobil)
mobil

   Produk              Kelebihan       Kekurangan
0  Toyota          Service Mudah      Pelit Fitur
1   Mazda           Fun to Drive  CBU harga mahal
2  Cherry  Murah tapi ga murahan      Service Bad
3     BMW                  Mewah    Service Mahal

In [9]:
laptop = {
    'Merek'      : ['Lenovo', 'HP', 'Acer', 'Asus'],
    'Kelebihan'  : ['Part Bagus', 'Murah', 'Pilihan Banyak', 'Ergonomis'],
    'Kekurangan' : ['Mahal', 'Plastik Laptop gampang patah', 'Keyboar suka rusak', 'Mesin gampang panas']
}

laptop = pd.DataFrame(laptop)
laptop

    Merek       Kelebihan                    Kekurangan
0  Lenovo      Part Bagus                         Mahal
1      HP           Murah  Plastik Laptop gampang patah
2    Acer  Pilihan Banyak            Keyboar suka rusak
3    Asus       Ergonomis           Mesin gampang panas

List of list

In [14]:
hp = [
    ['Apple', 'alat pembayaran di hotel', 'Claim garansi sulit'],
    ['Samsung', 'hardware optimal', 'pelangi di layar'],
    ['Vivo', 'Paling murah dari Flagship lain', 'Dikira hp murah']
]

hp = pd.DataFrame(hp, columns=['Merk', 'Kelebihan', 'Kekurangan'])
hp

      Merk                        Kelebihan           Kekurangan
0    Apple         alat pembayaran di hotel  Claim garansi sulit
1  Samsung                 hardware optimal     pelangi di layar
2     Vivo  Paling murah dari Flagship lain      Dikira hp murah

In [10]:
laptop = [
    ['Lenovo', 'Part Bagus', 'Mahal'],
    ['HP', 'Murah', 'Plastik gampang patah'],
    ['Acer', 'Pilihan Banyak', 'Keyboard suka rusak'],
    ['Asus', 'Ergonomis bentuknya', 'Gampang Overheat']
]

laptop = pd.DataFrame(laptop, columns=['Merek', 'Kelebihan', 'Kekurangan'])
laptop

    Merek            Kelebihan             Kekurangan
0  Lenovo           Part Bagus                  Mahal
1      HP                Murah  Plastik gampang patah
2    Acer       Pilihan Banyak    Keyboard suka rusak
3    Asus  Ergonomis bentuknya       Gampang Overheat

List of Dictionary

In [15]:
mineral = [
    {'Produk' : 'Aqua', 'Kelebihan' : 'Mudah ditemukan dibanyak warung', 'Kekurangan' : 'Overated'},
    {'Produk' : 'Le Mineral', 'Kelebihan' : 'Botol bagus', 'Kekurangan' : 'Mahal ga jelas'},
    {'Produk' : 'Vit', 'Kelebihan' : 'Murah', 'Kekurangan' : 'Diragukan kualitas airnya'}
]

mineral = pd.DataFrame(mineral)
mineral

       Produk                        Kelebihan                 Kekurangan
0        Aqua  Mudah ditemukan dibanyak warung                   Overated
1  Le Mineral                      Botol bagus             Mahal ga jelas
2         Vit                            Murah  Diragukan kualitas airnya

In [12]:
laptop = [
    {'Merk' : 'Lenovo', 'Kelebihan' : 'Part Laptop Bagus', 'Kekurangan' : 'Mahal'},
    {'Merk' : 'HP', 'Kekurangan' : 'Plastik gampang patah'},
    {'Merk' : 'Acer', 'Kelebihan' : 'Murah'},
    {'Merk' : 'Asus', 'Kekurangan' : 'Gampang panas'}
]

laptop = pd.DataFrame(laptop)
laptop

     Merk          Kelebihan             Kekurangan
0  Lenovo  Part Laptop Bagus                  Mahal
1      HP                NaN  Plastik gampang patah
2    Acer              Murah                    NaN
3    Asus                NaN          Gampang panas